config/routes.rb
Auth::Application.routes.draw do
  get "homes/index"
  root :to => "sessions#new"
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  resources :users
  resources :sessions
  resources :homes

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    redirect_to root_url unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to homes_path, :notice => "Logged in"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.haml
%h1 Homes

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Geekhmer Auth
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header.navbar.navbar-inverse.navbar-fixed-top.bs-docs-nav{role: "banner"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".bs-navbar-collapse", "data-toggle" => "collapse", type: "button"}
          %a.navbar-brand{href: "#"} Geek Auth
        %nav.collapse.navbar-collapse.bs-navbar-collapse{role: "navigation"}
          %ul.nav.navbar-nav.navbar-right
            - if current_user
              %li
                = link_to "Logged in as #{current_user.email}"
              %li
                = link_to "Log out", log_out_path
            - else
              %li
                = link_to "Sign up", sign_up_path
              %li
                = link_to "Log in", log_in_path
    .container
      - flash.each do |name, msg|
        .alert.alert-success
          = content_tag :div, msg, :id => "flash_#{name}"
      = yield

app/views/users/new.html.haml
%h2 Sign Up
= form_for @user do |f|
  - if @user.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - for message in @user.errors.full_messages
          %li= message
  %p
    = f.label :email
    %br
    = f.text_field :email, class: "form-control"
  %p
    = f.label :password
    %br
    = f.password_field :password, class: "form-control"
  %p
    = f.label :password_confirmation
    %br
    = f.password_field :password_confirmation, class: "form-control"
  = f.submit class: 'btn btn-default'